---
services:
  currency-exchange-microservice:
    image: library/currency-exchange-microservice:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - 8000:8000
    networks:
      - currency-network
    depends_on:
      - naming-server
      - zipkin-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT_TRACING_ZIPKIN_TRACING_ENDPOINT: http://zipkin-server:9411/api/v2/spans
  naming-server:
    image: library/naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - 8761:8761
    networks:
      - currency-network
  currency-conversion-service:
    image: library/currency-conversion-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - 8100:8100
    networks:
      - currency-network
    depends_on:
      - naming-server
      - zipkin-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT_TRACING_ZIPKIN_TRACING_ENDPOINT: http://zipkin-server:9411/api/v2/spans
  api-gateway:
    image: library/api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - 8765:8765
    networks:
      - currency-network
    depends_on:
      - naming-server
      - zipkin-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT_TRACING_ZIPKIN_TRACING_ENDPOINT: http://zipkin-server:9411/api/v2/spans
  zipkin-server:
    image: openzipkin/zipkin:2.23
    mem_limit: 300m
    ports:
      - "9411:9411"
    networks:
      - currency-network
    restart: always #Restart if there is a problem starting up
networks:
  currency-network: {}